//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servak.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseWorkDBEntities1 : DbContext
    {
        public CourseWorkDBEntities1()
            : base("name=CourseWorkDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<EventsList> EventsList { get; set; }
        public virtual DbSet<Experts> Experts { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
