//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork_SAIPIS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronym { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CarType { get; set; }
        public int InvoiceNumber { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Users Users { get; set; }
    }
}
